monolog:
    handlers:
        file_log:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        syslog_handler:
            type: syslog
            level: error